grafana:
  service:
    type: LoadBalancer

prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
    - job_name: jenkins
      metrics_path: '/prometheus'
      static_configs:
      - targets:
        - jenkins.jenkins.svc.cluster.local:8080
