apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2022-11-10T04:31:59Z"
    generation: 1
    labels:
      app: myapp
    name: myapp
    namespace: default
    resourceVersion: "18698"
    uid: c0a72681-f00a-47e6-9521-0d9dd439e304
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: myapp
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: myapp
      spec:
        containers:
        - image: ghcr.io/c1t1d0s7/go-myweb:alpine
          imagePullPolicy: IfNotPresent
          name: go-myweb
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2022-11-10T04:32:02Z"
      lastUpdateTime: "2022-11-10T04:32:02Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2022-11-10T04:31:59Z"
      lastUpdateTime: "2022-11-10T04:32:02Z"
      message: ReplicaSet "myapp-75d7879f5" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
